### PR TITLE
Fix definition php post size. Error in PHP 7.1.

### PR DESCRIPTION
**Pull request by VaLeXaR**

### CODE REVIEW

**Comment by ladislavsulc** [comment]
+1

**Comment by colthreepv** [comment]
LGTM

**Comment by cbracco** [comment]
LGTM!

**Comment by corysimmons** [comment]
Added this here: https://github.com/corysimmons/wp-sync-db/archive/1.6.zip

**Comment by slang800** [comment]
handled by https://github.com/wp-sync-db/wp-sync-db/pull/142

**Pull request closed without merging**
